# Generated by Django 5.2.4 on 2025-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='소속명')),
                ('type', models.CharField(choices=[('SCHOOL', '학교'), ('COMPANY', '회사'), ('ETC', '기타')], default='COMPANY', max_length=50, verbose_name='소속 종류')),
            ],
            options={
                'verbose_name': '소속',
                'verbose_name_plural': '소속(들)',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STAFF', '스태프'), ('INSTRUCTOR', '강사'), ('USER', '일반사용자')], default='USER', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='affiliations',
            field=models.ManyToManyField(blank=True, to='users.affiliation', verbose_name='소속'),
        ),
    ]
