### 사용자 회원가입 테스트
POST http://127.0.0.1:8000/api/v1/users/register/
Content-Type: application/json

{
    "username": "testuser_new",
    "email": "new_test@example.com",
    "password": "somepassword123"
}

### 사용자 로그인 테스트
POST http://127.0.0.1:8000/api/v1/users/login/
Content-Type: application/json

{
    "username": "testuser_new",
    "password": "new_strong_password456"
}

### 내 정보 보기 테스트 (인증 성공)
GET http://127.0.0.1:8000/api/v1/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMTM2NjYzLCJpYXQiOjE3NTIxMzYzNjMsImp0aSI6IjQyMGVlYjIzNzI5ZjQ1ZTQ5YjQ2ZWQwN2E2Y2M5ODY4IiwidXNlcl9pZCI6MX0.1S38GePSc0VJ6sf6yue5u1OjOhP5uA3tw-_lAIz0XK4


### 내 정보 보기 테스트 (인증 실패)
GET http://127.0.0.1:8000/api/v1/users/me/


### 강사 목록 조회 테스트
GET http://127.0.0.1:8000/api/v1/instructors/

### 비밀번호 변경 테스트
PUT http://127.0.0.1:8000/api/v1/users/password/change/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMTM2NjYzLCJpYXQiOjE3NTIxMzYzNjMsImp0aSI6IjQyMGVlYjIzNzI5ZjQ1ZTQ5YjQ2ZWQwN2E2Y2M5ODY4IiwidXNlcl9pZCI6MX0.1S38GePSc0VJ6sf6yue5u1OjOhP5uA3tw-_lAIz0XK4

{
    "old_password": "somepassword123",
    "new_password": "new_strong_password456"
}