# Generated by Django 5.2.4 on 2025-07-10 06:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, help_text='강사 소개')),
                ('expertise', models.CharField(blank=True, help_text='전문 분야', max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='경력 (년수)')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalInstructorProfile',
            fields=[
                ('bio', models.TextField(blank=True, help_text='강사 소개')),
                ('expertise', models.CharField(blank=True, help_text='전문 분야', max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='경력 (년수)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical instructor profile',
                'verbose_name_plural': 'historical instructor profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
