# Generated by Django 5.2.4 on 2025-07-10 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='전문 분야명')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalinstructorprofile',
            name='expertise',
        ),
        migrations.AddField(
            model_name='historicalinstructorprofile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, verbose_name='소속'),
        ),
        migrations.AddField(
            model_name='historicalinstructorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='historicalinstructorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, verbose_name='소속'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='historicalinstructorprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='강사 소개'),
        ),
        migrations.AlterField(
            model_name='historicalinstructorprofile',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='historicalinstructorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='경력 (년수)'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='강사 소개'),
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='expertise',
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='경력 (년수)'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='실적/프로젝트명')),
                ('description', models.TextField(blank=True, verbose_name='상세 내용')),
                ('achieved_date', models.DateField(blank=True, null=True, verbose_name='달성일')),
                ('instructor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='instructors.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='회사/기관명')),
                ('position', models.CharField(max_length=255, verbose_name='직책')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('description', models.TextField(blank=True, verbose_name='담당업무')),
                ('instructor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_history', to='instructors.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='자격증명')),
                ('issuer', models.CharField(max_length=255, verbose_name='발급기관')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='취득일')),
                ('instructor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='instructors.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='학교명')),
                ('major', models.CharField(max_length=255, verbose_name='전공')),
                ('degree', models.CharField(max_length=100, verbose_name='학위')),
                ('start_date', models.DateField(verbose_name='입학 연월')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='졸업 연월')),
                ('instructor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='instructors.instructorprofile', verbose_name='강사 프로필')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='논문/출간물 제목')),
                ('publisher', models.CharField(max_length=255, verbose_name='학회/출판사')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='발행일')),
                ('instructor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='instructors.instructorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='instructors.expertise', verbose_name='전문 분야'),
        ),
    ]
