# Generated by Django 5.2.4 on 2025-07-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_expertise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': '주요 실적', 'verbose_name_plural': '주요 실적(들)'},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': '경력', 'verbose_name_plural': '경력(들)'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': '자격 및 이수', 'verbose_name_plural': '자격 및 이수(들)'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': '학력', 'verbose_name_plural': '학력(들)'},
        ),
        migrations.AlterModelOptions(
            name='expertise',
            options={'verbose_name': '전문 분야', 'verbose_name_plural': '전문 분야(들)'},
        ),
        migrations.AlterModelOptions(
            name='historicalinstructorprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 강사 프로필', 'verbose_name_plural': 'historical 강사 프로필(들)'},
        ),
        migrations.AlterModelOptions(
            name='instructorprofile',
            options={'verbose_name': '강사 프로필', 'verbose_name_plural': '강사 프로필(들)'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': '논문 및 출간', 'verbose_name_plural': '논문 및 출간(들)'},
        ),
        migrations.AddField(
            model_name='career',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='career_proofs/', verbose_name='경력 증빙 자료'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_documen',
            field=models.FileField(blank=True, null=True, upload_to='education_degrees/', verbose_name='학위 증명서'),
        ),
    ]
