# Generated by Django 5.2.4 on 2025-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_alter_achievement_options_alter_career_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstructorprofile',
            name='profile_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='프로필 사진'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_profiles/', verbose_name='프로필 사진'),
        ),
    ]
